_BASE_: config://piece_classifier/_base_yolo.yaml

TRAINING:
  MODEL:
    REGISTRY: PIECE_CLASSIFIER
    NAME: CustomYOLO
    MODEL_PATH: ""  # Path to your custom YOLO model file (.pt)

YOLO:
  INPUT_SIZE: [640, 640]
  CONFIDENCE_THRESHOLD: 0.5
  IOU_THRESHOLD: 0.4
  CLASSES:
    - black_bishop
    - black_king
    - black_knight
    - black_pawn
    - black_queen
    - black_rook
    - white_bishop
    - white_king
    - white_knight
    - white_pawn
    - white_queen
    - white_rook
