DATASET:
  PATH: data://pieces
  CLASSES:
    - black_bishop
    - black_king
    - black_knight
    - black_pawn
    - black_queen
    - black_rook
    - white_bishop
    - white_king
    - white_knight
    - white_pawn
    - white_queen
    - white_rook
  BATCH_SIZE: 1
  WORKERS: 2
  TRANSFORMS:
    CENTER_CROP: null
    RESIZE: [640, 640]
    RANDOM_HORIZONTAL_FLIP: null
    COLOR_JITTER:
      BRIGHTNESS: 0.
      CONTRAST: 0.
      SATURATION: 0.
      HUE: 0.
    SHEAR: null
    SCALE:
      VERTICAL: null
      HORIZONTAL: null
    TRANSLATE:
      VERTICAL: null
      HORIZONTAL: null

TRAINING:
  USE_YOLO: true
  MODEL:
    REGISTRY: PIECE_CLASSIFIER
    NAME: YOLOv8
    MODEL_PATH: "/Users/shellmayr/code/chess-yolo/models/chess_comprehensive_20250820_095632/weights/best.pt"
  PHASES:
    - EPOCHS: 0
      OPTIMIZER:
        LEARNING_RATE: 0.001
        NAME: Adam
      PARAMS: all

YOLO:
  INPUT_SIZE: [640, 640]
  CONFIDENCE_THRESHOLD: 0.5
  IOU_THRESHOLD: 0.4
  MAX_DETECTIONS: 32
  DEVICE: "auto"
